cpupower_helper: Fix FileNotFoundError
Do not call .read_text() on the governor_path file if it does not exist.
Without this check, there is the following FileNotFoundError:

FileNotFoundError: [Errno 2] No such file or directory:
'/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors'

BUG=b:218521368
TEST=CQ

Change-Id: I810919550ebf1b81130426831d2771df247f4fe6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3556027
Reviewed-by: Ram Chandrasekar <rchandrasekar@google.com>
Tested-by: Cindy Lin <xcl@google.com>
Commit-Queue: Cindy Lin <xcl@google.com>