qemu: s/EEXISTS/EEXIST/
Ironically, the EEXISTS flag does not exist.

  AttributeError: module 'errno' has no attribute 'EEXISTS'

BUG=none
TEST=you don't want to know how I got here

Change-Id: Ia55f9a116659d691521fe336aa9105086fea1b87
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2304004
Tested-by: Brian Norris <briannorris@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>