vm: Require --board to be specified on the cmd-line.
If you run `cros_vm --start` in a chrome checkout outside the Simple
Chrome shell and forget to pass in --board, it leads to some
unintuitive errors like:
 WARNING: Using system QEMU.
 ERROR: QEMU not found.

Which happens since the code needs to know the board to find the right
QEMU inside the Simple Chrome cache. Adding this check should ensure
folks don't forget to pass in --board.

BUG=chromium:937821
TEST=unittest

Change-Id: I4fc8c80ff20f2f901c4fc7ab945a8f3af15f5145
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2268282
Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Tested-by: Ben Pastene <bpastene@chromium.org>