Revert "cros_build_lib: run: drop deprecated output=/error= APIs"
This reverts commit 29eefd5c5296cf87bbe5d3859123ac9ebcba5c54.

Reason for revert: breaks "cros flash":

% cros flash usb:// xbuddy://remote/ghost/latest-dev/test
Removable device(s) found. Please select/confirm to continue:
  [0]: SanDisk USB Extreme Pro 238.5G (/dev/sda)
Please choose an option [0-0]: 0
13:09:49: ERROR: cros flash failed before completing.
13:09:49: ERROR: 'CommandResult' object has no attribute 'output'
13:09:49: ERROR: (Re-run with --debug for more details.)

Original change's description:
> cros_build_lib: run: drop deprecated output=/error= APIs
>
> Everything should be migrated, so drop old support.
>
> BUG=b:187789262
> TEST=CQ passes
>
> Change-Id: Ibe122d44b4f6f1c27f9ed38197aaf90fa47335be
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3789868
> Commit-Queue: Mike Frysinger <vapier@chromium.org>
> Tested-by: Mike Frysinger <vapier@chromium.org>
> Reviewed-by: Sergey Frolov <sfrolov@google.com>

Bug: b:187789262
Change-Id: I9a745d52696c2bb0c4725834feca03bd9e91c786
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3795854
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>