cros lint: drop automatic PYTHONPATH for pylint
This logic has been in here since we first added pylint support back
in 2012.  This has probably outlived its usefulness at this point:
* Portage stopped installing into /usr/lib/portage/pym/ years ago.
* We haven't imported anything from src/platform/ for years.
* The implicit dirname search breaks when modules clash.

With the Python 2 -> 3, we've encouraged people to structure their
code differently to support (or not) relative imports directly.

The last point can be seen when linting some chromite modules like:
$ cros lint format/formatters/json.py
Traceback (most recent call last):
  File ".../chromite/scripts/pylint", line 67, in <module>
    from pylint import lint
  File ".../python3.8/site-packages/pylint/__init__.py", line 15, in <module>
    from pylint.__pkginfo__ import __version__
  File ".../python3.8/site-packages/pylint/__pkginfo__.py", line 4, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File ".../python3.8/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File ".../python3/lib/python3.8/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File ".../chromite/format/formatters/xml.py", line 10, in <module>
    from xml.etree import ElementTree
ModuleNotFoundError: No module named 'xml.etree'; 'xml' is not a package
08:48:58: ERROR: Found lint errors in 1 files in 0.444s.

This is because we have a file named "xml.py" which clashes with the
system xml import.

BUG=b:187785601
TEST=`cros lint` doesn't show any new warnings in chromite

Change-Id: I3426c43f978f678e5e08f771247fc46594d58ae8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3668394
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Lizzy Presland <zland@google.com>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Lizzy Presland <zland@google.com>