Revert "Artifacts service: add support for license_credits.html"
This reverts commit 2ffee8ae6a2f012f1868bc902abf3b23adffcf99.

Reason for revert: Breaks all CQ / snapshot builder.
https://ci.chromium.org/ui/p/chromeos/builders/cq/cave-cq/b8843043761431824992/overview
NotADirectoryError: [Errno 20] Not a directory: '/b/s/w/ir/x/w/recipe_cleanup/chromiumos_workspace/src/build/images/cave/latest/license_credits.html'
(shutil.copytree doesn't work for a single file.)

Original change's description:
> Artifacts service: add support for license_credits.html
>
> BUG=b:191479981
> TEST=unit tests (no coverage for relevant endpoint, though)
>
> Change-Id: Ibf03f934ebed4d6f1ca537b8b2f24e79233bf1bc
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2972282
> Reviewed-by: Alex Klein <saklein@chromium.org>
> Reviewed-by: George Engelbrecht <engeg@google.com>
> Tested-by: Jack Neus <jackneus@google.com>
> Commit-Queue: Jack Neus <jackneus@google.com>

Bug: b:191479981
Change-Id: I0ef950cd2ab4fc36bc5931e59c207bacb2d7f3e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/2994320
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>