git: Handle the ignore_missing case
If the missing is ignored, we should return None.

BUG=None
TEST=(1) ./scripts/run_tests \
lib/git_unittest.py::ManifestHashTest::testGetManifestHashIgnoreMissing
     (2) Without this change, fails with "AttributeError: 'str' object
     has no attribute 'seek'".
     (3) With this change, passes.

Change-Id: I1934f69bb99b462a3cfbb666fa9e3cc44ec66bf8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3479052
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Cheng Yueh <cyueh@chromium.org>
Commit-Queue: Cheng Yueh <cyueh@chromium.org>