Revert "package-service: add support for alternative kernel patterns"
This reverts commit 8e14eb1bb14a1b1c958c0b68991c6fb07da702c4.

Reason for revert: This actually breaks every board, `FlattenedDepsForPackage` is not returning just the single kernel version...

```
chromite.service.packages.KernelVersionError: Too many packages found in FlattenedDepsForPackage (virtual/linux-sources-1sys-kernel/chromeos-kernel-4_4-4.4.302-r2828sys-kernel/chromeos-kernel-4_14-4.14.277-r1869sys-kernel/chromeos-kernel-4_19-4.19.241-r2337sys-kernel/chromeos-kernel-5_4-5.4.191-r3135sys-kernel/chromeos-kernel-5_10-5.10.113-r1883sys-kernel/chromeos-kernel-5_15-5.15.37-r406sys-kernel/chromeos-kernel-experimental-4.18_rc2-r23sys-kernel/chromeos-kernel-next-9999sys-kernel/chromeos-kernel-upstream-5.18_rc3-r68sys-kernel/upstream-kernel-mainline-9999sys-kernel/upstream-kernel-next-9999virtual/linux-sources-1-r30sys-kernel/chromeos-kernel-4_4-4.4.302-r2828sys-kernel/chromeos-kernel-4_14-4.14.277-r1869sys-kernel/chromeos-kernel-4_19-4.19.241-r2337sys-kernel/chromeos-kernel-5_4-5.4.191-r3135sys-kernel/chromeos-kernel-5_10-5.10.113-r1883sys-kernel/chromeos-kernel-5_15-5.15.37-r406sys-kernel/chromeos-kernel-experimental-4.18_rc2-r23sys-kernel/chromeos-kernel-next-9999sys-kernel/chromeos-kernel-upstream-5.18_rc3-r68sys-kernel/upstream-kernel-mainline-9999sys-kernel/upstream-kernel-next-9999)
```

Original change's description:
> package-service: add support for alternative kernel patterns
>
> Some boards (e.g. beaglebone) use their own custom kernel, and as such
> are not being caught by `determine_kernel_version`. Add logic to support
> their kernel, as well as changing the signature of the method to not
> return `None` (because the proto field doesn't support None).
>
> BUG=None
> TEST=unit-test
>
> Change-Id: Icb2218c3df7b8203eb5b3a7e9862f4d011687511
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3615656
> Reviewed-by: George Engelbrecht <engeg@google.com>
> Reviewed-by: Mike Frysinger <vapier@chromium.org>
> Tested-by: Benjamin Shai <bshai@google.com>
> Commit-Queue: Benjamin Shai <bshai@google.com>

Bug: None
Change-Id: I1c3003755b005a9b199c4b3d3287c9ec04bca716
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/chromite/+/3632021
Reviewed-by: George Engelbrecht <engeg@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Mike Frysinger <vapier@chromium.org>